### ISSUE TITLE
多列等高布局

### ISSUE THREAD

**Issue by Bloom2036** [Bloom2036/frontEndDemo#12]
html
```html
<div id="container">
  <div class="left">多列等高布局左</div> 
  <div class="right">多列等高布局,使用正负 margin 与 padding 相冲的方式实现。多列等高布局,使用正负 margin 与 padding 相冲的方式实现。</div>
</div>
```

css
```css
#container{
	width:400px;
	margin:0 auto;
	background:#eee;
	overflow:hidden;
}

.left,
.right{
	width:200px;
	float:left;
	font-size: 16px;
	line-height:24px;
	color:#333;
	padding-bottom:5000px;
	margin-bottom:-5000px;
}

.left{
	background-color: deeppink;
}

.right{
	background-color:yellowgreen;
}
```
效果图
![image](https://user-images.githubusercontent.com/18345542/31885733-2996a18c-b7b7-11e7-9115-f4bccbbd8341.png)
